# Site settings
title            : Test blog
email            : arturovolpe@gmail.com
description      : ""
baseurl          : ""
url              : "http                                                                                                                                                                                                      : //yourdomain.com"
twitter_username : cochovolpe
github_username  : avolpe

# Build settings
markdown         : kramdown
permalink        : pretty
